// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SayParam struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayParam) Reset()         { *m = SayParam{} }
func (m *SayParam) String() string { return proto.CompactTextString(m) }
func (*SayParam) ProtoMessage()    {}
func (*SayParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_48a9839ee4742117, []int{0}
}
func (m *SayParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayParam.Unmarshal(m, b)
}
func (m *SayParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayParam.Marshal(b, m, deterministic)
}
func (dst *SayParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayParam.Merge(dst, src)
}
func (m *SayParam) XXX_Size() int {
	return xxx_messageInfo_SayParam.Size(m)
}
func (m *SayParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SayParam.DiscardUnknown(m)
}

var xxx_messageInfo_SayParam proto.InternalMessageInfo

func (m *SayParam) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SayResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayResponse) Reset()         { *m = SayResponse{} }
func (m *SayResponse) String() string { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()    {}
func (*SayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_48a9839ee4742117, []int{1}
}
func (m *SayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayResponse.Unmarshal(m, b)
}
func (m *SayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayResponse.Marshal(b, m, deterministic)
}
func (dst *SayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayResponse.Merge(dst, src)
}
func (m *SayResponse) XXX_Size() int {
	return xxx_messageInfo_SayResponse.Size(m)
}
func (m *SayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayResponse proto.InternalMessageInfo

func (m *SayResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SayParam)(nil), "model.SayParam")
	proto.RegisterType((*SayResponse)(nil), "model.SayResponse")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_common_48a9839ee4742117) }

var fileDescriptor_common_48a9839ee4742117 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x03, 0x73, 0x84, 0x58, 0x73, 0xf3, 0x53,
	0x52, 0x73, 0x94, 0x64, 0xb8, 0x38, 0x82, 0x13, 0x2b, 0x03, 0x12, 0x8b, 0x12, 0x73, 0x85, 0x04,
	0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x79,
	0x2e, 0xee, 0xe0, 0xc4, 0xca, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x4c, 0x05, 0x46,
	0xa6, 0x5c, 0xcc, 0xc1, 0x89, 0x95, 0x42, 0x7a, 0x5c, 0xac, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x42,
	0xfc, 0x7a, 0x60, 0x63, 0xf5, 0x60, 0x66, 0x4a, 0x09, 0x21, 0x04, 0x60, 0xc6, 0x28, 0x31, 0x24,
	0xb1, 0x81, 0xdd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x93, 0x1e, 0xdf, 0x6b, 0x99, 0x00,
	0x00, 0x00,
}
